# Generated by Django 5.0.1 on 2024-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=50)),
                ('Middle', models.CharField(max_length=50)),
                ('Last', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=150)),
            ],
        ),
    ]
