# Generated by Django 5.0.1 on 2024-02-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='District',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Last',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Middle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Province',
        ),
        migrations.AlterField(
            model_name='contact',
            name='First',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
