# Generated by Django 5.0.1 on 2024-02-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_district_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstn', models.TextField(max_length=100)),
                ('last', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('add', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('room', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
            ],
        ),
    ]
