# Generated by Django 5.0.1 on 2024-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookr_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookr',
            name='add',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookr',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookr',
            name='email',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookr',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookr',
            name='last',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookr',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
