# Generated by Django 5.0.1 on 2024-02-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bookr_add_alter_bookr_city_alter_bookr_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookr',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
