# Generated by Django 5.0.2 on 2024-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_registeru'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=20)),
                ('arrival_date', models.DateTimeField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('enterby', models.CharField(max_length=20)),
            ],
        ),
    ]
