# Generated by Django 5.0.2 on 2024-02-14 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_register_customer_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_customer',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
