# Generated by Django 5.0.2 on 2024-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_register_customer_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_customer',
            name='arrival_date',
            field=models.CharField(max_length=20),
        ),
    ]
