# Generated by Django 5.0.2 on 2024-02-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_register_customer_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_customer',
            name='arrival_date',
        ),
    ]
